### ISSUE TITLE
NoSuchMethodError: com.intellij.openapi.vfs.VirtualFile.exists()Z

### ISSUE THREAD

**Issue by jtulach** [Baratynskiy/kotlin-netbeans#113]
I am using constantly (on every change in editor) getting following error when using Kotlin in my Maven project from recent NetBeans:
```
INFO [org.jetbrains.kotlin.log.KotlinLogger]: Analyzing http://github.com/jtulach/bck2brwsr/benchmarks/sieve/src/test/java/org/apidesign/benchmark/sieve/kotlin/SieveTest.kt
SEVERE [org.openide.util.Exceptions]
java.lang.NoSuchMethodError: com.intellij.openapi.vfs.VirtualFile.exists()Z
        at org.jetbrains.kotlin.resolve.KotlinPackagePartProvider.processNotLoadedRelevantRoots(KotlinPackagePartProvider.kt:77)
        at org.jetbrains.kotlin.resolve.KotlinPackagePartProvider.getPackageParts(KotlinPackagePartProvider.kt:48)
        at org.jetbrains.kotlin.resolve.KotlinPackagePartProvider.findPackageParts(KotlinPackagePartProvider.kt:25)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaPackageFragment$binaryClasses$2.invoke(LazyJavaPackageFragment.kt:37)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaPackageFragment$binaryClasses$2.invoke(LazyJavaPackageFragment.kt:32)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:323)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:364)
        at org.jetbrains.kotlin.storage.StorageKt.getValue(storage.kt:39)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaPackageFragment.getBinaryClasses$kotlin_compiler(LazyJavaPackageFragment.kt)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.JvmPackageScope$kotlinScopes$2.invoke(JvmPackageScope.kt:44)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.JvmPackageScope$kotlinScopes$2.invoke(JvmPackageScope.kt:36)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:323)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:364)
        at org.jetbrains.kotlin.storage.StorageKt.getValue(storage.kt:39)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.JvmPackageScope.getKotlinScopes(JvmPackageScope.kt)
        at org.jetbrains.kotlin.load.java.lazy.descriptors.JvmPackageScope.getContributedDescriptors(JvmPackageScope.kt:71)
        at org.jetbrains.kotlin.resolve.scopes.ChainedMemberScope.getContributedDescriptors(ChainedMemberScope.kt:42)
        at org.jetbrains.kotlin.resolve.scopes.AbstractScopeAdapter.getContributedDescriptors(AbstractScopeAdapter.kt:53)
        at org.jetbrains.kotlin.resolve.scopes.ResolutionScope$DefaultImpls.getContributedDescriptors$default(ResolutionScope.kt:37)
        at org.jetbrains.kotlin.resolve.lazy.DefaultImportProvider$excludedImports$2.invoke(DefaultImportProvider.kt:49)
        at org.jetbrains.kotlin.resolve.lazy.DefaultImportProvider$excludedImports$2.invoke(DefaultImportProvider.kt:35)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:323)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:364)
        at org.jetbrains.kotlin.storage.StorageKt.getValue(storage.kt:39)
        at org.jetbrains.kotlin.resolve.lazy.DefaultImportProvider.getExcludedImports(DefaultImportProvider.kt)
        at org.jetbrains.kotlin.resolve.lazy.FileScopeFactory.createScopesForFile(FileScopeFactory.kt:105)
        at org.jetbrains.kotlin.resolve.lazy.FileScopeFactory.createScopesForFile$default(FileScopeFactory.kt:62)
        at org.jetbrains.kotlin.resolve.lazy.FileScopeProviderImpl$cache$1.invoke(FileScopeProvider.kt:46)
        at org.jetbrains.kotlin.resolve.lazy.FileScopeProviderImpl$cache$1.invoke(FileScopeProvider.kt:38)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:402)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:470)
        at org.jetbrains.kotlin.resolve.lazy.FileScopeProviderImpl.getFileScopes(FileScopeProvider.kt:51)
        at org.jetbrains.kotlin.resolve.lazy.FileScopeProvider$DefaultImpls.getFileResolutionScope(FileScopeProvider.kt:28)
        at org.jetbrains.kotlin.resolve.lazy.FileScopeProviderImpl.getFileResolutionScope(FileScopeProvider.kt:38)
        at org.jetbrains.kotlin.resolve.lazy.DeclarationScopeProviderImpl.getResolutionScopeForDeclaration(DeclarationScopeProviderImpl.java:60)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor.getOuterScope(LazyClassDescriptor.java:351)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor$9.invoke(LazyClassDescriptor.java:259)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor$9.invoke(LazyClassDescriptor.java:256)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$scopeForClassHeaderResolution$1.invoke(ClassResolutionScopesSupport.kt:42)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$scopeForClassHeaderResolution$1.invoke(ClassResolutionScopesSupport.kt:30)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:323)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:364)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor.getScopeForClassHeaderResolution(LazyClassDescriptor.java:357)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor.computeSupertypes(LazyClassDescriptor.java:731)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor$LazyClassTypeConstructor.computeSupertypes(LazyClassDescriptor.java:643)
        at org.jetbrains.kotlin.types.AbstractTypeConstructor$supertypes$1.invoke(AbstractTypeConstructor.kt:35)
        at org.jetbrains.kotlin.types.AbstractTypeConstructor$supertypes$1.invoke(AbstractTypeConstructor.kt:22)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:323)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:364)
        at org.jetbrains.kotlin.types.AbstractTypeConstructor.getSupertypes(AbstractTypeConstructor.kt:23)
        at org.jetbrains.kotlin.types.AbstractTypeConstructor.getSupertypes(AbstractTypeConstructor.kt:22)
        at org.jetbrains.kotlin.resolve.descriptorUtil.DescriptorUtilsKt.getSuperClassNotAny(DescriptorUtils.kt:134)
        at org.jetbrains.kotlin.resolve.descriptorUtil.DescriptorUtilsKt.getAllSuperclassesWithoutAny(DescriptorUtils.kt:348)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$inheritanceScopeWithoutMe$1.invoke(ClassResolutionScopesSupport.kt:50)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$inheritanceScopeWithoutMe$1.invoke(ClassResolutionScopesSupport.kt:30)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:323)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:364)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$inheritanceScopeWithMe$1.invoke(ClassResolutionScopesSupport.kt:56)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$inheritanceScopeWithMe$1.invoke(ClassResolutionScopesSupport.kt:30)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:323)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:364)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$scopeForMemberDeclarationResolution$1.invoke(ClassResolutionScopesSupport.kt:64)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$scopeForMemberDeclarationResolution$1.invoke(ClassResolutionScopesSupport.kt:30)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:323)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:364)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor.getScopeForMemberDeclarationResolution(LazyClassDescriptor.java:375)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassMemberScope.getScopeForMemberDeclarationResolution(LazyClassMemberScope.kt:99)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope.doGetFunctions(AbstractLazyMemberScope.kt:85)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope.access$doGetFunctions(AbstractLazyMemberScope.kt:39)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope$functionDescriptors$1.invoke(AbstractLazyMemberScope.kt:49)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope$functionDescriptors$1.invoke(AbstractLazyMemberScope.kt:39)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:402)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:470)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope.getContributedFunctions(AbstractLazyMemberScope.kt:77)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassMemberScope.getContributedFunctions(LazyClassMemberScope.kt:127)
        at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver$1.visitNamedFunction(LazyDeclarationResolver.java:167)
        at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver$1.visitNamedFunction(LazyDeclarationResolver.java:118)
        at org.jetbrains.kotlin.psi.KtNamedFunction.accept(KtNamedFunction.java:48)
        at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver.resolveToDescriptor(LazyDeclarationResolver.java:118)
        at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver.resolveToDescriptor(LazyDeclarationResolver.java:113)
        at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.createFunctionDescriptors(LazyTopDownAnalyzer.kt:252)
        at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations(LazyTopDownAnalyzer.kt:190)
        at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations$default(LazyTopDownAnalyzer.kt:56)
        at org.jetbrains.kotlin.resolve.NetBeansAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(NetBeansAnalyzerFacadeForJVM.kt:143)
        at org.jetbrains.kotlin.resolve.KotlinAnalyzer.analyzeFile(KotlinAnalyzer.kt:29)
        at org.jetbrains.kotlin.diagnostics.netbeans.parser.KotlinParser$Companion.analyze(KotlinParser.kt:46)
        at org.jetbrains.kotlin.diagnostics.netbeans.parser.KotlinParser$Companion.getAnalysisResult(KotlinParser.kt:43)
        at org.jetbrains.kotlin.diagnostics.netbeans.parser.KotlinParser.parse(KotlinParser.kt:73)
        at org.netbeans.modules.parsing.impl.TaskProcessor.callParse(TaskProcessor.java:621)
        at org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:251)
        at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:798)
        at org.openide.util.lookup.Lookups.executeWith(Lookups.java:304)
        at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:725)
[catch] at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:686)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
        at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
        at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
        at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
```
looks like a packaging problem to me, but I have no idea how it could happen. I just installed the Kotlin plugin from the plugin portal. Here is the dump of files I have in my NetBeans `--userdir`:
```
nbuserdir$ find | grep kotlin
./modules/ext/Kotlin.kotlin.netbeans.plugin
./modules/ext/Kotlin.kotlin.netbeans.plugin/com-google-guava
./modules/ext/Kotlin.kotlin.netbeans.plugin/com-google-guava/guava.jar
./modules/ext/Kotlin.kotlin.netbeans.plugin/dom4j
./modules/ext/Kotlin.kotlin.netbeans.plugin/dom4j/dom4j.jar
./modules/ext/Kotlin.kotlin.netbeans.plugin/org-jetbrains-kotlin
./modules/ext/Kotlin.kotlin.netbeans.plugin/org-jetbrains-kotlin/intellij-core.jar
./modules/ext/Kotlin.kotlin.netbeans.plugin/org-jetbrains-kotlin/kotlin-converter.jar
./modules/ext/Kotlin.kotlin.netbeans.plugin/org-jetbrains-kotlin/kotlin-formatter.jar
./modules/ext/Kotlin.kotlin.netbeans.plugin/org-jetbrains-kotlin/asm.jar
./modules/ext/Kotlin.kotlin.netbeans.plugin/org-jetbrains-kotlin/kotlin-compiler.jar
./modules/ext/Kotlin.kotlin.netbeans.plugin/org-jetbrains-kotlin/kotlin-ide-common.jar
./modules/ext/Kotlin.kotlin.netbeans.plugin/org-jetbrains-kotlin/idea-formatter.jar
./modules/ext/Kotlin.kotlin.netbeans.plugin/org-jetbrains-kotlin/openapi-formatter.jar
./modules/ext/Kotlin.kotlin.netbeans.plugin/commons-io
./modules/ext/Kotlin.kotlin.netbeans.plugin/commons-io/commons-io.jar
./modules/ext/Kotlin.kotlin.netbeans.plugin/org-netbeans-external
./modules/ext/Kotlin.kotlin.netbeans.plugin/org-netbeans-external/nb-javac-api.jar
./modules/ext/Kotlin.kotlin.netbeans.plugin/org-netbeans-external/asm-all-5.0.1.jar
./modules/Kotlin-kotlin-netbeans-plugin.jar
./__MACOSX/kotlinc
./__MACOSX/kotlinc/._lib
./__MACOSX/kotlinc/lib
./__MACOSX/kotlinc/lib/._kotlin-test.jar
./__MACOSX/kotlinc/lib/._kotlin-stdlib-sources.jar
./__MACOSX/kotlinc/lib/._kotlin-compiler.jar
./__MACOSX/kotlinc/lib/._kotlin-stdlib-js-sources.jar
./__MACOSX/kotlinc/lib/._kotlin-ant.jar
./__MACOSX/kotlinc/lib/._kotlin-preloader.jar
./__MACOSX/kotlinc/lib/._kotlin-jslib-sources.jar
./__MACOSX/kotlinc/lib/._kotlin-test-js.jar
./__MACOSX/kotlinc/lib/._kotlin-runtime-sources.jar
./__MACOSX/kotlinc/lib/._kotlin-runner.jar
./__MACOSX/kotlinc/lib/._kotlin-daemon-client.jar
./__MACOSX/kotlinc/lib/._kotlin-runtime.jar
./__MACOSX/kotlinc/lib/._android-extensions-compiler.jar
./__MACOSX/kotlinc/lib/._kotlin-annotation-processing.jar
./__MACOSX/kotlinc/lib/._kotlin-stdlib.jar
./__MACOSX/kotlinc/lib/._kotlin-script-runtime-sources.jar
./__MACOSX/kotlinc/lib/._kotlin-build-common-test.jar
./__MACOSX/kotlinc/lib/._noarg-compiler-plugin.jar
./__MACOSX/kotlinc/lib/._kotlin-reflect.jar
./__MACOSX/kotlinc/lib/._kotlin-jslib.jar
./__MACOSX/kotlinc/lib/._allopen-compiler-plugin.jar
./__MACOSX/kotlinc/lib/._kotlin-stdlib-js.jar
./__MACOSX/kotlinc/lib/._kotlin-script-runtime.jar
./__MACOSX/kotlinc/lib/._sam-with-receiver-compiler-plugin.jar
./__MACOSX/kotlinc/._build.txt
./__MACOSX/kotlinc/._.DS_Store
./__MACOSX/._kotlinc
./config/Modules/Kotlin-kotlin-netbeans-plugin.xml
./update_tracking/Kotlin-kotlin-netbeans-plugin.xml
./kotlinc
./kotlinc/build.txt
./kotlinc/lib
./kotlinc/lib/kotlin-script-runtime.jar
./kotlinc/lib/kotlin-runner.jar
./kotlinc/lib/kotlin-test.jar
./kotlinc/lib/kotlin-ant.jar
./kotlinc/lib/kotlin-annotation-processing.jar
./kotlinc/lib/sam-with-receiver-compiler-plugin.jar
./kotlinc/lib/allopen-compiler-plugin.jar
./kotlinc/lib/kotlin-jslib-sources.jar
./kotlinc/lib/kotlin-stdlib-sources.jar
./kotlinc/lib/kotlin-runtime-sources.jar
./kotlinc/lib/kotlin-runtime.jar
./kotlinc/lib/kotlin-stdlib-js.jar
./kotlinc/lib/android-extensions-compiler.jar
./kotlinc/lib/kotlin-build-common-test.jar
./kotlinc/lib/kotlin-compiler.jar
./kotlinc/lib/kotlin-daemon-client.jar
./kotlinc/lib/kotlin-jslib.jar
./kotlinc/lib/noarg-compiler-plugin.jar
./kotlinc/lib/kotlin-stdlib-js-sources.jar
./kotlinc/lib/kotlin-script-runtime-sources.jar
./kotlinc/lib/kotlin-preloader.jar
./kotlinc/lib/kotlin-test-js.jar
./kotlinc/lib/kotlin-stdlib.jar
./kotlinc/lib/kotlin-reflect.jar
./kotlinc/.DS_Store
nbuserdir$ cat ./update_tracking/Kotlin-kotlin-netbeans-plugin.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<module codename="Kotlin.kotlin.netbeans.plugin">
    <module_version last="true" origin="Plugin portal" specification_version="0.2.0">
        <file crc="899433706" name="config/Modules/Kotlin-kotlin-netbeans-plugin.xml"/>
        <file crc="611135577" name="modules/Kotlin-kotlin-netbeans-plugin.jar"/>
        <file crc="3059859154" name="modules/ext/Kotlin.kotlin.netbeans.plugin/com-google-guava/guava.jar"/>
        <file crc="937643154" name="modules/ext/Kotlin.kotlin.netbeans.plugin/commons-io/commons-io.jar"/>
        <file crc="2050839146" name="modules/ext/Kotlin.kotlin.netbeans.plugin/dom4j/dom4j.jar"/>
        <file crc="790635419" name="modules/ext/Kotlin.kotlin.netbeans.plugin/org-jetbrains-kotlin/asm.jar"/>
        <file crc="820349971" name="modules/ext/Kotlin.kotlin.netbeans.plugin/org-jetbrains-kotlin/idea-formatter.jar"/>
        <file crc="1462898749" name="modules/ext/Kotlin.kotlin.netbeans.plugin/org-jetbrains-kotlin/intellij-core.jar"/>
        <file crc="1299630168" name="modules/ext/Kotlin.kotlin.netbeans.plugin/org-jetbrains-kotlin/kotlin-compiler.jar"/>
        <file crc="1467181438" name="modules/ext/Kotlin.kotlin.netbeans.plugin/org-jetbrains-kotlin/kotlin-converter.jar"/>
        <file crc="2213164034" name="modules/ext/Kotlin.kotlin.netbeans.plugin/org-jetbrains-kotlin/kotlin-formatter.jar"/>
        <file crc="104577701" name="modules/ext/Kotlin.kotlin.netbeans.plugin/org-jetbrains-kotlin/kotlin-ide-common.jar"/>
        <file crc="841772044" name="modules/ext/Kotlin.kotlin.netbeans.plugin/org-jetbrains-kotlin/openapi-formatter.jar"/>
        <file crc="2977601252" name="modules/ext/Kotlin.kotlin.netbeans.plugin/org-netbeans-external/asm-all-5.0.1.jar"/>
        <file crc="1391129566" name="modules/ext/Kotlin.kotlin.netbeans.plugin/org-netbeans-external/nb-javac-api.jar"/>
        <file crc="3682330682" name="update_tracking/Kotlin-kotlin-netbeans-plugin.xml"/>
    </module_version>
</module>
```

**Comment by stefanciprian** [comment]
Same here:
```

java.lang.NoSuchMethodError: com.intellij.openapi.vfs.VirtualFile.exists()Z
	at org.jetbrains.kotlin.resolve.KotlinPackagePartProvider.processNotLoadedRelevantRoots(KotlinPackagePartProvider.kt:77)
	at org.jetbrains.kotlin.resolve.KotlinPackagePartProvider.getPackageParts(KotlinPackagePartProvider.kt:48)
	at org.jetbrains.kotlin.resolve.KotlinPackagePartProvider.findPackageParts(KotlinPackagePartProvider.kt:25)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaPackageFragment$binaryClasses$2.invoke(LazyJavaPackageFragment.kt:37)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaPackageFragment$binaryClasses$2.invoke(LazyJavaPackageFragment.kt:32)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:323)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:364)
	at org.jetbrains.kotlin.storage.StorageKt.getValue(storage.kt:39)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaPackageFragment.getBinaryClasses$kotlin_compiler(LazyJavaPackageFragment.kt)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.JvmPackageScope$kotlinScopes$2.invoke(JvmPackageScope.kt:44)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.JvmPackageScope$kotlinScopes$2.invoke(JvmPackageScope.kt:36)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:323)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:364)
	at org.jetbrains.kotlin.storage.StorageKt.getValue(storage.kt:39)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.JvmPackageScope.getKotlinScopes(JvmPackageScope.kt)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.JvmPackageScope.getContributedDescriptors(JvmPackageScope.kt:71)
	at org.jetbrains.kotlin.resolve.scopes.ChainedMemberScope.getContributedDescriptors(ChainedMemberScope.kt:42)
	at org.jetbrains.kotlin.resolve.scopes.AbstractScopeAdapter.getContributedDescriptors(AbstractScopeAdapter.kt:53)
	at org.jetbrains.kotlin.resolve.scopes.ResolutionScope$DefaultImpls.getContributedDescriptors$default(ResolutionScope.kt:37)
	at org.jetbrains.kotlin.resolve.lazy.DefaultImportProvider$excludedImports$2.invoke(DefaultImportProvider.kt:49)
	at org.jetbrains.kotlin.resolve.lazy.DefaultImportProvider$excludedImports$2.invoke(DefaultImportProvider.kt:35)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:323)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:364)
	at org.jetbrains.kotlin.storage.StorageKt.getValue(storage.kt:39)
	at org.jetbrains.kotlin.resolve.lazy.DefaultImportProvider.getExcludedImports(DefaultImportProvider.kt)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeFactory.createScopesForFile(FileScopeFactory.kt:105)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeFactory.createScopesForFile$default(FileScopeFactory.kt:62)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeProviderImpl$cache$1.invoke(FileScopeProvider.kt:46)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeProviderImpl$cache$1.invoke(FileScopeProvider.kt:38)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:402)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:470)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeProviderImpl.getFileScopes(FileScopeProvider.kt:51)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeProvider$DefaultImpls.getFileResolutionScope(FileScopeProvider.kt:28)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeProviderImpl.getFileResolutionScope(FileScopeProvider.kt:38)
	at org.jetbrains.kotlin.resolve.lazy.DeclarationScopeProviderImpl.getResolutionScopeForDeclaration(DeclarationScopeProviderImpl.java:60)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor.getOuterScope(LazyClassDescriptor.java:351)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor$9.invoke(LazyClassDescriptor.java:259)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor$9.invoke(LazyClassDescriptor.java:256)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$scopeForClassHeaderResolution$1.invoke(ClassResolutionScopesSupport.kt:42)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$scopeForClassHeaderResolution$1.invoke(ClassResolutionScopesSupport.kt:30)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:323)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:364)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor.getScopeForClassHeaderResolution(LazyClassDescriptor.java:357)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor.computeSupertypes(LazyClassDescriptor.java:731)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor$LazyClassTypeConstructor.computeSupertypes(LazyClassDescriptor.java:643)
	at org.jetbrains.kotlin.types.AbstractTypeConstructor$supertypes$1.invoke(AbstractTypeConstructor.kt:35)
	at org.jetbrains.kotlin.types.AbstractTypeConstructor$supertypes$1.invoke(AbstractTypeConstructor.kt:22)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:323)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:364)
	at org.jetbrains.kotlin.types.AbstractTypeConstructor.getSupertypes(AbstractTypeConstructor.kt:23)
	at org.jetbrains.kotlin.types.AbstractTypeConstructor.getSupertypes(AbstractTypeConstructor.kt:22)
	at org.jetbrains.kotlin.resolve.descriptorUtil.DescriptorUtilsKt.getSuperClassNotAny(DescriptorUtils.kt:134)
	at org.jetbrains.kotlin.resolve.descriptorUtil.DescriptorUtilsKt.getAllSuperclassesWithoutAny(DescriptorUtils.kt:348)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$inheritanceScopeWithoutMe$1.invoke(ClassResolutionScopesSupport.kt:50)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$inheritanceScopeWithoutMe$1.invoke(ClassResolutionScopesSupport.kt:30)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:323)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:364)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$inheritanceScopeWithMe$1.invoke(ClassResolutionScopesSupport.kt:56)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$inheritanceScopeWithMe$1.invoke(ClassResolutionScopesSupport.kt:30)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:323)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:364)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$scopeForMemberDeclarationResolution$1.invoke(ClassResolutionScopesSupport.kt:64)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$scopeForMemberDeclarationResolution$1.invoke(ClassResolutionScopesSupport.kt:30)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:323)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:364)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor.getScopeForMemberDeclarationResolution(LazyClassDescriptor.java:375)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassMemberScope.getScopeForMemberDeclarationResolution(LazyClassMemberScope.kt:99)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope.doGetFunctions(AbstractLazyMemberScope.kt:85)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope.access$doGetFunctions(AbstractLazyMemberScope.kt:39)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope$functionDescriptors$1.invoke(AbstractLazyMemberScope.kt:49)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope$functionDescriptors$1.invoke(AbstractLazyMemberScope.kt:39)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:402)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:470)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope.getContributedFunctions(AbstractLazyMemberScope.kt:77)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassMemberScope.getContributedFunctions(LazyClassMemberScope.kt:127)
	at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver$1.visitNamedFunction(LazyDeclarationResolver.java:167)
	at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver$1.visitNamedFunction(LazyDeclarationResolver.java:118)
	at org.jetbrains.kotlin.psi.KtNamedFunction.accept(KtNamedFunction.java:48)
	at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver.resolveToDescriptor(LazyDeclarationResolver.java:118)
	at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver.resolveToDescriptor(LazyDeclarationResolver.java:113)
	at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.createFunctionDescriptors(LazyTopDownAnalyzer.kt:252)
	at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations(LazyTopDownAnalyzer.kt:190)
	at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations$default(LazyTopDownAnalyzer.kt:56)
	at org.jetbrains.kotlin.resolve.NetBeansAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(NetBeansAnalyzerFacadeForJVM.kt:143)
	at org.jetbrains.kotlin.resolve.KotlinAnalyzer.analyzeFile(KotlinAnalyzer.kt:29)
	at org.jetbrains.kotlin.diagnostics.netbeans.parser.KotlinParser$Companion.analyze(KotlinParser.kt:46)
	at org.jetbrains.kotlin.diagnostics.netbeans.parser.KotlinParser$Companion.getAnalysisResult(KotlinParser.kt:43)
	at org.jetbrains.kotlin.diagnostics.netbeans.parser.KotlinParser.parse(KotlinParser.kt:73)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callParse(TaskProcessor.java:621)
	at org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:251)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:798)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:304)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:725)
[catch] at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:686)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

```

Is it related to this https://mvnrepository.com/artifact/com.intellij/openapi/7.0.3 ?

**Comment by Kaszaq** [comment]
This is a blocker, can you please assist? My project I created in IntelliJ doesnt boot in Netbeans with your plugin.

**Comment by baratynskiy** [comment]
Fixed in the latest plugin release: https://github.com/JetBrains/kotlin-netbeans/releases/tag/v0.2.0.1

**Comment by jtulach** [comment]
Don't you want to upload the plugin to http://plugins.netbeans.org? I've just installed fresh NetBeans 8.2 and downloaded Kotlin plugin and noticed the problem is still there (in spite of being fixed in your above referenced version).
